### ISSUE TITLE
创建VPN 时提示错误

### ISSUE THREAD

**Issue by alatan** [iamldj/Detour#7]
![tim 20171226203111](https://user-images.githubusercontent.com/3773229/34356841-7242b892-ea7c-11e7-8120-902b0cdc50f2.jpg)

**Comment by 2493947748** [comment]
![1862162522](https://user-images.githubusercontent.com/34996640/35547384-bbde61de-05b3-11e8-8c1e-60003e6ad904.jpg)
![1740962972](https://user-images.githubusercontent.com/34996640/35547386-bc532442-05b3-11e8-9168-57b5ad3c0969.jpg)
